spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/checkout
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: select 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: checkout
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        shca_sql: true
        use_sql_comments: true

        
